// <auto-generated />
using System;
using MapMemo.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MapMemo.Api.Data.Migrations
{
    [DbContext(typeof(MapMemoDbContext))]
    [Migration("20260225072317_ReplaceIntersectionWithJunction")]
    partial class ReplaceIntersectionWithJunction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MapMemo.Api.Data.Entities.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("Added")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("Updated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("city", (string)null);
                });

            modelBuilder.Entity("MapMemo.Api.Data.Entities.Junction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Lat")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("lat");

                    b.Property<decimal>("Lng")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("lng");

                    b.Property<long?>("RoundaboutId")
                        .HasColumnType("bigint")
                        .HasColumnName("roundabout_id");

                    b.Property<string>("WayType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("way_type");

                    b.HasKey("Id");

                    b.HasIndex("RoundaboutId")
                        .HasDatabaseName("idx_junction_roundabout_id");

                    b.ToTable("junction", (string)null);
                });

            modelBuilder.Entity("MapMemo.Api.Data.Entities.OsmWay", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long>("RoadId")
                        .HasColumnType("bigint")
                        .HasColumnName("road_id");

                    b.HasKey("Id");

                    b.HasIndex("RoadId")
                        .HasDatabaseName("idx_osm_way_road_id");

                    b.ToTable("osm_way", (string)null);
                });

            modelBuilder.Entity("MapMemo.Api.Data.Entities.Road", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CityId")
                        .HasColumnType("bigint")
                        .HasColumnName("city_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CityId")
                        .HasDatabaseName("idx_road_city_id");

                    b.HasIndex("CityId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_road_city_name");

                    b.ToTable("road", (string)null);
                });

            modelBuilder.Entity("MapMemo.Api.Data.Entities.RoadJunction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("JunctionId")
                        .HasColumnType("bigint")
                        .HasColumnName("junction_id");

                    b.Property<int>("NodeIndex")
                        .HasColumnType("integer")
                        .HasColumnName("node_index");

                    b.Property<long>("RoadId")
                        .HasColumnType("bigint")
                        .HasColumnName("road_id");

                    b.HasKey("Id");

                    b.HasIndex("JunctionId")
                        .HasDatabaseName("idx_road_junction_junction_id");

                    b.HasIndex("RoadId")
                        .HasDatabaseName("idx_road_junction_road_id");

                    b.ToTable("road_junction", (string)null);
                });

            modelBuilder.Entity("MapMemo.Api.Data.Entities.Roundabout", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CityId")
                        .HasColumnType("bigint")
                        .HasColumnName("city_id");

                    b.HasKey("Id");

                    b.HasIndex("CityId")
                        .HasDatabaseName("idx_roundabout_city_id");

                    b.ToTable("roundabout", (string)null);
                });

            modelBuilder.Entity("MapMemo.Api.Data.Entities.Junction", b =>
                {
                    b.HasOne("MapMemo.Api.Data.Entities.Roundabout", "Roundabout")
                        .WithMany("Junctions")
                        .HasForeignKey("RoundaboutId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Roundabout");
                });

            modelBuilder.Entity("MapMemo.Api.Data.Entities.OsmWay", b =>
                {
                    b.HasOne("MapMemo.Api.Data.Entities.Road", "Road")
                        .WithMany("OsmWays")
                        .HasForeignKey("RoadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Road");
                });

            modelBuilder.Entity("MapMemo.Api.Data.Entities.Road", b =>
                {
                    b.HasOne("MapMemo.Api.Data.Entities.City", "City")
                        .WithMany("Roads")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("MapMemo.Api.Data.Entities.RoadJunction", b =>
                {
                    b.HasOne("MapMemo.Api.Data.Entities.Junction", "Junction")
                        .WithMany("RoadJunctions")
                        .HasForeignKey("JunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MapMemo.Api.Data.Entities.Road", "Road")
                        .WithMany("RoadJunctions")
                        .HasForeignKey("RoadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Junction");

                    b.Navigation("Road");
                });

            modelBuilder.Entity("MapMemo.Api.Data.Entities.Roundabout", b =>
                {
                    b.HasOne("MapMemo.Api.Data.Entities.City", "City")
                        .WithMany("Roundabouts")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("MapMemo.Api.Data.Entities.City", b =>
                {
                    b.Navigation("Roads");

                    b.Navigation("Roundabouts");
                });

            modelBuilder.Entity("MapMemo.Api.Data.Entities.Junction", b =>
                {
                    b.Navigation("RoadJunctions");
                });

            modelBuilder.Entity("MapMemo.Api.Data.Entities.Road", b =>
                {
                    b.Navigation("OsmWays");

                    b.Navigation("RoadJunctions");
                });

            modelBuilder.Entity("MapMemo.Api.Data.Entities.Roundabout", b =>
                {
                    b.Navigation("Junctions");
                });
#pragma warning restore 612, 618
        }
    }
}
