// <auto-generated />
using System;
using MapMemo.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MapMemo.Api.Data.Migrations
{
    [DbContext(typeof(MapMemoDbContext))]
    partial class MapMemoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MapMemo.Api.Data.Entities.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("Added")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("Updated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("city", (string)null);
                });

            modelBuilder.Entity("MapMemo.Api.Data.Entities.Intersection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Lat")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("lat");

                    b.Property<decimal>("Lng")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("lng");

                    b.Property<long>("RoadAId")
                        .HasColumnType("bigint")
                        .HasColumnName("road_a_id");

                    b.Property<long>("RoadBId")
                        .HasColumnType("bigint")
                        .HasColumnName("road_b_id");

                    b.Property<string>("WayType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("way_type");

                    b.HasKey("Id");

                    b.HasIndex("RoadAId")
                        .HasDatabaseName("idx_intersection_road_a_id");

                    b.HasIndex("RoadBId")
                        .HasDatabaseName("idx_intersection_road_b_id");

                    b.ToTable("intersection", (string)null);
                });

            modelBuilder.Entity("MapMemo.Api.Data.Entities.IntersectionSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IntersectionId")
                        .HasColumnType("bigint")
                        .HasColumnName("intersection_id");

                    b.Property<long>("NodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("node_id");

                    b.Property<long>("OsmWayId")
                        .HasColumnType("bigint")
                        .HasColumnName("osm_way_id");

                    b.HasKey("Id");

                    b.HasIndex("IntersectionId")
                        .HasDatabaseName("idx_intersection_source_intersection_id");

                    b.HasIndex("OsmWayId")
                        .HasDatabaseName("idx_intersection_source_osm_way_id");

                    b.ToTable("intersection_source", (string)null);
                });

            modelBuilder.Entity("MapMemo.Api.Data.Entities.OsmWay", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long>("RoadId")
                        .HasColumnType("bigint")
                        .HasColumnName("road_id");

                    b.HasKey("Id");

                    b.HasIndex("RoadId")
                        .HasDatabaseName("idx_osm_way_road_id");

                    b.ToTable("osm_way", (string)null);
                });

            modelBuilder.Entity("MapMemo.Api.Data.Entities.Road", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CityId")
                        .HasColumnType("bigint")
                        .HasColumnName("city_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CityId")
                        .HasDatabaseName("idx_road_city_id");

                    b.HasIndex("CityId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_road_city_name");

                    b.ToTable("road", (string)null);
                });

            modelBuilder.Entity("MapMemo.Api.Data.Entities.Intersection", b =>
                {
                    b.HasOne("MapMemo.Api.Data.Entities.Road", "RoadA")
                        .WithMany()
                        .HasForeignKey("RoadAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MapMemo.Api.Data.Entities.Road", "RoadB")
                        .WithMany()
                        .HasForeignKey("RoadBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoadA");

                    b.Navigation("RoadB");
                });

            modelBuilder.Entity("MapMemo.Api.Data.Entities.IntersectionSource", b =>
                {
                    b.HasOne("MapMemo.Api.Data.Entities.Intersection", "Intersection")
                        .WithMany("IntersectionSources")
                        .HasForeignKey("IntersectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MapMemo.Api.Data.Entities.OsmWay", "OsmWay")
                        .WithMany("IntersectionSources")
                        .HasForeignKey("OsmWayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intersection");

                    b.Navigation("OsmWay");
                });

            modelBuilder.Entity("MapMemo.Api.Data.Entities.OsmWay", b =>
                {
                    b.HasOne("MapMemo.Api.Data.Entities.Road", "Road")
                        .WithMany("OsmWays")
                        .HasForeignKey("RoadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Road");
                });

            modelBuilder.Entity("MapMemo.Api.Data.Entities.Road", b =>
                {
                    b.HasOne("MapMemo.Api.Data.Entities.City", "City")
                        .WithMany("Roads")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("MapMemo.Api.Data.Entities.City", b =>
                {
                    b.Navigation("Roads");
                });

            modelBuilder.Entity("MapMemo.Api.Data.Entities.Intersection", b =>
                {
                    b.Navigation("IntersectionSources");
                });

            modelBuilder.Entity("MapMemo.Api.Data.Entities.OsmWay", b =>
                {
                    b.Navigation("IntersectionSources");
                });

            modelBuilder.Entity("MapMemo.Api.Data.Entities.Road", b =>
                {
                    b.Navigation("OsmWays");
                });
#pragma warning restore 612, 618
        }
    }
}
